### ISSUE TITLE
Fix windows build and test

### ISSUE THREAD

**Issue by wuyingnan** [RobSimulatorGroup/gobot#38]
Currently windows build and test is disabled because there are bugs in CMakeLists.txt. Need to fix it and enable windows build/test again

**Comment by wuyingnan** [comment]
Reference for 0xC0000135

https://discourse.cmake.org/t/cmake-build-and-test-with-qt-and-google-test/4729
https://stackoverflow.com/questions/28533012/how-to-set-runtime-path-for-cmake-custom-command-on-windows

**Comment by Wuqiqi123** [comment]
Copy gtest.dll gmock.dll gtest_main.dll  gmock.dll gmock_main.dll and librttr_core_d.dll into test directory will solve this issue.

**Comment by Wuqiqi123** [comment]
Also modify this "https://raw.githubusercontent.com/wuyingnan/cmake-conan/develop/conan.cmake"
